simui/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import simuiWeb.urls as core

from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(core, namespace='core')),
]

simuiWeb/urls.py
from django.conf.urls import url
from .views import index

from .views import *
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^list_organisasi/',list_organisasi, name='list_organisasi'),
    url(r'^create_organisasi/',create_organisasi, name='create_organisasi'),
    url(r'^update_organisasi/(?P<id>[\w|\W]+)/$',update_organisasi, name='update_organisasi'),
    url(r'^list_kepanitiaan/',list_kepanitiaan, name='list_kepanitiaan'),
    url(r'^create_kepanitiaan/',create_kepanitiaan, name='create_kepanitiaan'),
    url(r'^update_kepanitiaan/(?P<id>[\w|\W]+)/$',update_kepanitiaan, name='update_kepanitiaan'),
    url(r'^list_event/',list_event, name='list_event'),
    url(r'^create_event/',create_event, name='create_event'),
    url(r'^update_event/(?P<id>[\w|\W]+)/$',update_event, name='update_event'),
    url(r'^show_login/',show_login, name='show_login'),
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^delete_organisasi/(?P<id>[\w|\W]+)/$',delete_organisasi, name='delete_organisasi'),
    url(r'^delete_kepanitiaan/(?P<id>[\w|\W]+)/$',delete_kepanitiaan, name='delete_kepanitiaan'),
    url(r'^delete_event/(?P<id>[\w|\W]+)/$',delete_event, name='delete_event'),
    url(r'^add_org/', add_org, name='add_org'),
    url(r'^update_org/', update_org, name='update_org'),
    url(r'^add_kepanitiaan/', add_kepanitiaan, name='add_kepanitiaan'),
    url(r'^update_panit/', update_panit, name='update_panit'),
    url(r'^add_event/', add_event, name='add_event'),
    url(r'^update_ev/', update_ev, name='update_event'),
]

simuiWeb/models.py
from django.db import models

# Create your models here.

simuiWeb/views.py
from django.shortcuts import render
from django.db import connection

from django.urls import reverse

from django.http import Http404

import http.client
import json
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

import random
import string
import datetime
from random import randint

response = {}
def index(request):
	cursor = connection.cursor()
	cursor.execute("SELECT nama from SIMUI.PEMBUAT_EVENT, SIMUI.ORGANISASI where id = id_organisasi LIMIT 5")
	list_organisasi = []
	cursor_all = cursor.fetchall()
	if len(cursor_all) > 0:
		columns = [name[0] for name in cursor.description]
		for x in cursor_all:
			list_organisasi.append(dict(zip(columns, x)))
	response['list_organisasi'] = list_organisasi
	cursor.execute("SELECT nama from SIMUI.PEMBUAT_EVENT, SIMUI.KEPANITIAAN where id = id_kepanitiaan LIMIT 5")
	list_kepanitiaan = []
	cursor_all = cursor.fetchall()
	if len(cursor_all) > 0:
		columns = [name[0] for name in cursor.description]
		for x in cursor_all:
			list_kepanitiaan.append(dict(zip(columns, x)))
	response['list_kepanitiaan'] = list_kepanitiaan
	cursor.execute("SELECT nama from SIMUI.PEMBUAT_EVENT LIMIT 5")
	list_event = []
	cursor_all = cursor.fetchall()
	if len(cursor_all) > 0:
		columns = [name[0] for name in cursor.description]
		for x in cursor_all:
			list_event.append(dict(zip(columns, x)))
	response['list_event'] = list_event
	return render(request, 'LandingPage.html', response)
def show_login(request):
	response['message'] = "yes"
	if ("role" in request.session):
		return HttpResponseRedirect(reverse('core:index'))
	return render(request, 'login.html', response)
def list_organisasi(request):
	cursor = connection.cursor()
	cursor.execute("SELECT * from SIMUI.PEMBUAT_EVENT, SIMUI.ORGANISASI where id = id_organisasi")
	list_organisasi = []
	cursor_all = cursor.fetchall()
	if len(cursor_all) > 0:
		columns = [name[0] for name in cursor.description]
		for x in cursor_all:
			list_organisasi.append(dict(zip(columns, x)))

	response['list'] = list_organisasi
	return render(request,'ListOrganisasi.html', response)
def update_organisasi(request, id):
	request.session['id'] = id
	cursor = connection.cursor()
	cursor.execute("SELECT nama,email,alamat_website,tingkatan,kategori,logo,deskripsi,contact_person from SIMUI.PEMBUAT_EVENT where id = '"+id+"'")
	select = cursor.fetchone()
	response['nama'] = select[0]
	response['email'] = select[1]
	response['website'] = select[2]
	response['tingkatan'] = select[3]
	response['kategori'] = select[4]
	response['logo'] = select[5]
	response['deskripsi'] = select[6]
	response['cp'] = select[7]
	return render(request,'OrganisasiUpdate.html', response)
def create_organisasi(request):
	return render(request,'OrganisasiFill.html', response)
def delete_organisasi(request, id):
	theidInt = int(id)
	theid = str(theidInt - 1)
	print(theid)
	cursor=connection.cursor()
	cursor.execute("DELETE from simui.organisasi where id_organisasi = '"+id+"'")
	cursor.execute("DELETE from simui.pembuat_event where id = '"+id+"'")
	return HttpResponseRedirect(reverse('core:list_organisasi'))
def list_kepanitiaan(request):
    cursor = connection.cursor()
    cursor.execute("SELECT k.id, k.nama as kepanitiaan, o.nama as organisasi,k.email,k.alamat_website,k.tingkatan,k.kategori,k.logo,k.deskripsi,k.contact_person from SIMUI.pembuat_event k, SIMUI.kepanitiaan , SIMUI.pembuat_event o where k.id = id_kepanitiaan and o.id = id_organisasi")
    list_kepanitiaan = []
    cursor_all = cursor.fetchall()
    if len(cursor_all) > 0:
        columns = [name[0] for name in cursor.description]
        for x in cursor_all:
            list_kepanitiaan.append(dict(zip(columns, x)))
    print(list_kepanitiaan)
    response['list'] = list_kepanitiaan
    return render(request,'ListKepanitiaan.html', response)
def update_kepanitiaan(request, id):
	request.session['id'] = id
	cursor = connection.cursor()
	cursor.execute("SELECT nama,email,alamat_website,tingkatan,kategori,logo,deskripsi,contact_person from SIMUI.PEMBUAT_EVENT where id = '"+id+"'")
	select = cursor.fetchone()
	response['nama'] = select[0]
	response['email'] = select[1]
	response['website'] = select[2]
	response['tingkatan'] = select[3]
	response['kategori'] = select[4]
	response['logo'] = select[5]
	response['deskripsi'] = select[6]
	response['cp'] = select[7]
	return render(request,'KepanitiaanUpdate.html', response)
def create_kepanitiaan(request):
	return render(request,'Kepanitiaanfill.html', response)
def delete_kepanitiaan(request, id):
	theidInt = int(id)
	theid = str(theidInt - 1)
	print(theid)
	cursor=connection.cursor()
	cursor.execute("DELETE from simui.kepanitiaan where id_kepanitiaan = '"+id+"'")
	cursor.execute("DELETE from simui.pembuat_event where id = '"+id+"'")
	return render(request,'ListKepanitiaan.html', response)
def list_event(request):
    cursor = connection.cursor()
    cursor.execute("SELECT id_event,id_pembuat_event,nama,tanggal,kapasitas,harga_tiket,lokasi,sifat_event,deskripsi_singkat,nomor_kategori,poster from SIMUI.EVENT")
    list_event = []
    cursor_all = cursor.fetchall()
    if len(cursor_all) > 0:
        columns = [name[0] for name in cursor.description]
        for x in cursor_all:
            list_event.append(dict(zip(columns, x)))
    response['list'] = list_event
    return render(request,'ListEvent.html', response)
def update_event(request, id):
	request.session['id'] = id
	cursor = connection.cursor()
	cursor.execute("SELECT nama,tanggal,kapasitas,harga_tiket,lokasi,sifat_event,deskripsi_singkat,nomor_kategori,poster from SIMUI.EVENT where id_event = '"+id+"'")
	select = cursor.fetchone()
	response['nama'] = select[0]
	response['tanggal'] = select[1]
	response['kapasitas'] = select[2]
	response['tiket'] = select[3]
	response['lokasi'] = select[4]
	response['sifat'] = select[5]
	response['deskripsi'] = select[6]
	response['kategori'] = select[7]
	response['poster'] = select[8]
	return render(request,'EventUpdate.html', response)
def create_event(request):
		return render(request,'EventFill.html', response)
def delete_event(request, id):
	theidInt = int(id)
	theid = str(theidInt - 1)
	print(theid)
	cursor=connection.cursor()
	cursor.execute("DELETE from simui.event where id_event = '"+id+"'")
	return render(request,'ListOrganisasi.html', response)
@csrf_exempt
def login(request):
	if(request.method == "POST"):
		username = request.POST['Username']
		password = request.POST['Password']
		cursor=connection.cursor()
		cursor.execute("SELECT * from SIMUI.PENGGUNA where username='"+username+"'")
		select=cursor.fetchone()
		if(select):
			print("user detect")
			cursor.execute("SELECT password from SIMUI.PENGGUNA where username='"+username+"'")
			select=cursor.fetchone()
			if select[0] == password:
				print("password detect")
				cursor.execute("SELECT * from SIMUI.STAFF where username='"+username+"'")
				select=cursor.fetchone()
				if(select):
					print("halo2")
					response['message'] = "yes"
					request.session['role'] = "humas"
					return HttpResponseRedirect(reverse('core:index'))
				cursor.execute("SELECT * from SIMUI.ADMIN where username='"+username+"'")
				select=cursor.fetchone()
				if(select):
					print("halo")
					response['message'] = "yes"
					request.session['role'] = "admin"
					return HttpResponseRedirect(reverse('core:index'))
				response['message'] = "yes"
				request.session['role'] = "non_admin"
				return HttpResponseRedirect(reverse('core:index'))
			else:
				response['message'] = "no"
				return render(request, 'login.html', response)
		else:
			response['message'] = "no"
			return render(request, 'login.html', response)
	response['message'] = "no"
	return render(request, 'login.html', response)
def logout(request):
		request.session.clear()
		return HttpResponseRedirect(reverse('core:index'))

@csrf_exempt
def add_org(request):
	if request.method == 'POST':
		cursor = connection.cursor()
		intg=randint(51, 99999)
		theid = request.session.get('theid',intg)
		theidStr = str(theid)
		print(theidStr)
		cursor.execute("SELECT id from SIMUI.PEMBUAT_EVENT where id = '"+theidStr+"'")
		select = cursor.fetchone()
		print(select)
		if(select):
			while(select[0] == intg):
				intg=randint(51, 99999)
				theid = request.session.get('theid',intg)

		print("id")
		print(theid)
		theidStr = str(theid)
		name = request.POST['name']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		cp = request.POST['cp']
		kategori = request.POST['kategori']
		logo = request.POST['logo']
		deskripsi = request.POST['des']

		cursor.execute("INSERT INTO simui.pembuat_event(id,nama,email,alamat_website,tingkatan,kategori,logo,deskripsi,contact_person) VALUES ('"+theidStr+"','"+name+"','"+email+"','"+website+"','"+tingkatan+"','"+kategori+"', '"+logo+"','"+deskripsi+"','"+cp+"')")
		cursor.execute("INSERT INTO simui.organisasi(id_organisasi) VALUES ('"+theidStr+"')")
		theidInt = int(theid)
		theidInt += 1
		request.session['theid'] = theidInt
	return HttpResponseRedirect(reverse('core:list_organisasi'))

@csrf_exempt
def update_org(request):
	print("masuk")
	if request.method == 'POST':
		cursor = connection.cursor()
		theid = request.session.get('id')
		name = request.POST['name']
		tingkatan = request.POST['tingkatan']
		email = request.POST['email']
		website = request.POST['website']
		cp = request.POST['cp']
		kategori = request.POST['kategori']
		logo = request.POST['logo']
		deskripsi = request.POST['des']
		cursor.execute("UPDATE SIMUI.PEMBUAT_EVENT SET nama = '"+name+"' , email = '"+email+"', alamat_website = '"+website+"', tingkatan = '"+tingkatan+"', kategori = '"+kategori+"', logo = '"+logo+"', deskripsi = '"+deskripsi+"', contact_person = '"+cp+"' where id = '"+theid+"' ")
	return HttpResponseRedirect(reverse('core:list_organisasi'))

@csrf_exempt
def add_kepanitiaan(request):
	if request.method == 'POST':
		cursor=connection.cursor()

simuiWeb/templates/EventFill.html
{% extends 'layout/base.html' %}
{% load static %}

{% block extension %}SIMUI - List Organisasi{% endblock %}

{% block content %}
         <div class="align-items-center d-flex cover screen3 py-5">
            <div class="container">
              <div class="row">
                <div class="col-lg-12 p-3">
                  <form class="p-4 bg-light" method="post" action="{% url 'core:add_event' %}">
                    <h4 class="mb-4 text-center">Tambahkan Event</h4>
                    {% csrf_token %}
                    <div class="form-group">
                      <label>Nama Event</label>
                      <input class="form-control" name="nama" placeholder="nama event"> </div>
                    <div class="form-group">
                      <label>Tanggal</label>
                      <input class="form-control" name="tanggal" placeholder="format: 2018-03-15"> </div>
                    <div class="form-group">
                      <label>Kapasitas</label>
                      <input type="number" class="form-control" name="kapasitas" placeholder="kapasitas"> </div>
                    <div class="form-group">
                      <label>Harga Tiket</label>
                      <input type="number" class="form-control" name="tiket" placeholder="harga"> </div> 
                    <div class="form-group">
                      <label>Lokasi</label>
                      <input class="form-control" name="lokasi" placeholder="lokasi" > </div> 
                    <div class="form-group">
                      <label>Sifat Event</label><br>
                      <select name="sifat" style="position: relative; left: 1rem">  
                        <option value="Umum"> Umum</option>
                        <option value="Private"> Private </option></div>
                      </select>
                     <div class="form-group">
                      <label>Kategori</label>
                      <select name="kategori" style="position: relative; left: 1rem">
                        <option selected value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                      </select> </div>
                    <div class="form-group">
                      <label>Deskripsi</label>
                      <input name="deskripsi" class="form-control" placeholder="deskripsi"> </div>
                    <div class="form-group">
                      <label>Poster</label>
                      <br><input type="file" name="poster" accept="image/*"> </div>
                    <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
                      <b>Tambahkan</b>
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <!-- Scripts -->
{% endblock %}

simuiWeb/templates/EventUpdate.html
{% extends 'layout/base.html' %}
{% load static %}

{% block extension %}SIMUI - List Organisasi{% endblock %}

{% block content %}
         <div class="align-items-center d-flex cover screen3 py-5">
            <div class="container">
              <div class="row">
                <div class="col-lg-12 p-3">
                  <form class="p-4 bg-light" method="post" action="{% url 'core:update_event' %}">
                    {% csrf_token %}
                    <h4 class="mb-4 text-center">Update Event</h4>
                    <div class="form-group">
                      <label>Nama Event</label>
                      <input class="form-control" name="nama" value="{{ nama }}"> </div>
                    <div class="form-group">
                      <label>Tanggal</label>
                      <input class="form-control" name="tanggal" value="2018-03-15"> </div>
                    <div class="form-group">
                      <label>Kapasitas</label>
                      <input type="number" class="form-control" name="kapasitas" value="{{ kapasitas }}" > </div>
                    <div class="form-group">
                      <label>Harga Tiket</label>
                      <input type="number" class="form-control" name="tiket" value="{{ tiket }}"> </div> 
                    <div class="form-group">
                      <label>Lokasi</label>
                      <input class="form-control" name="lokasi" value="{{ lokasi }}"> </div> 
                    <div class="form-group">
                      <label>Sifat Event</label><br>
                      <select name="sifat" style="position: relative; left: 1rem">
                      {% if sifat == 'Umum' %}  
                        <option value="Umum"> Umum</option>
                        <option value="Private"> Private </option></div>
                      {% elif sifat == 'Privat' %}
                        <option value="Umum"> Umum</option>
                        <option value="Private"> Private </option></div>
                       {% endif %} 
                      </select>
                     <div class="form-group">
                      <label>Kategori</label>
                      <select name="kategori" style="position: relative; left: 1rem">
                        
                        <option selected="selected" value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        
                      </select> </div>
                    <div class="form-group">
                      <label>Deskripsi</label>
                      <input name="des" class="form-control" value="{{ deskripsi }}"> </div>
                    <div class="form-group">
                      <label>Poster</label>
                      <br><input type="file" name="poster" accept="image/*"> </div>
                    <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
                      <b>Tambahkan</b>
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <!-- Scripts -->
{% endblock %}

simuiWeb/templates/ListEvent.html
{% extends 'layout/base.html' %}
{% load static %}

{% block extension %}SIMUI - ListKepanitiaan{% endblock %}

{% block content %}
{% if request.session.role == "humas" or request.session.role == "admin" %}
                <div class="screen3 container py-5">
            <h1>Event</h1> <td><a class="btn btn-success my-2 my-sm-0" style="position: absolute; right: -3rem; top: 3rem" type="submit" href="{% url 'core:create_event' %}" role = "button">Tambah Event</a>

            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>

                  <th scope="col">Nama Event</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Tanggal Mulai</th>
                  <th scope="col">Kapasitas</th>
                  <th scope="col">Harga_tiket</th>
                  <th scope="col">Lokasi</th>
                  <th scope="col">Sifat Event</th>
                  <th scope="col">Deskripsi_singkat</th>
                  <th scope="col">Poster</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for i in list %}
                <tr>
                  <td>{{ i.nama }}</td>
                  <td>{{ i.nomor_kategori }}</td>
                  <td>{{ i.tanggal }}</td>
                  <td>{{ i.kapasitas }}</td>
                  <td>{{ i.harga_tiket }}</td>
                  <td>{{ i.lokasi }}</td>
                  <td>{{ i.sifat_event }}</td>
                  <td>{{ i.deskripsi_singkat }}</td>
                  <td>{{ i.poster }}</td>
                  <td><a class="btn btn-primary my-2 my-sm-0" type="submit" role="button" href="{% url 'core:update_event' id=i.id_event %}">Update</a><a href="{% url 'core:delete_event' i.id_event %}" id="delete" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        {% else %}

        <div class="screen5 container py-5">
            <h1>Event</h1>

            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Nama Event</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Tanggal Mulai</th>
                  <th scope="col">Kapasitas</th>
                  <th scope="col">Harga_tiket</th>
                  <th scope="col">Lokasi</th>
                  <th scope="col">Sifat Event</th>
                  <th scope="col">Deskripsi_singkat</th>
                  <th scope="col">Poster</th>
                </tr>
              </thead>
              <tbody>
                {% for i in list %}
                <tr>
                  <td>{{ i.nama }}</td>
                  <td>{{ i.nomor_kategori }}</td>
                  <td>{{ i.tanggal }}</td>
                  <td>{{ i.kapasitas }}</td>
                  <td>{{ i.harga_tiket }}</td>
                  <td>{{ i.lokasi }}</td>
                  <td>{{ i.sifat_event }}</td>
                  <td>{{ i.deskripsi_singkat }}</td>
                  <td>{{ i.poster }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        {% endif %}
{% endblock %}

simuiWeb/templates/ListKepanitiaan.html
{% extends 'layout/base.html' %}
{% load static %}

{% block extension %}SIMUI - ListKepanitiaan{% endblock %}

{% block content %}
{% if request.session.role == "humas" or request.session.role == "admin" %}
        <div class="screen5 container py-5">
            <h1>Kepanitiaan</h1> <td><a class="btn btn-success my-2 my-sm-0" style="position: absolute; right: -4rem; top: 3rem" type="submit" role="button" href="{% url 'core:create_kepanitiaan' %}">Tambah Kepanitiaan</a>

            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Nama Kepanitiaan</th>
                  <th scope="col">Nama Organisasi</th>
                  <th scope="col">Email</th>
                  <th scope="col">Website</th>
                  <th scope="col">Tingkatan</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Logo</th>
                  <th scope="col">Deskripsi</th>
                  <th scope="col">Contact Person</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for i in list %}
                <tr>
                  <td>{{ i.kepanitiaan }}</td>
                  <td>{{ i.organisasi }}</td>
                  <td>{{ i.email }}</td>
                  <td>{{ i.alamat_website }}</td>
                  <td>{{ i.tingkatan }}</td>
                  <td>{{ i.kategori }}</td>
                  <td>{{ i.logo }}</td>
                  <td>{{ i.deskripsi }}</td>
                  <td>{{ i.contact_person }}</td>
                  <td><a class="btn btn-primary my-2 my-sm-0" type="submit" role="button" href="{% url 'core:update_kepanitiaan' id=i.id%}">Update</a><a href="{% url 'core:delete_kepanitiaan' i.id %}" id="delete" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

        {% else %}
        <div class="screen5 container py-5">
            <h1>Kepanitiaan</h1>

            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Nama Kepanitiaan</th>
                  <th scope="col">Nama Organisasi</th>
                  <th scope="col">Email</th>
                  <th scope="col">Website</th>
                  <th scope="col">Tingkatan</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Logo</th>
                  <th scope="col">Deskripsi</th>
                  <th scope="col">Contact Person</th>
                </tr>
              </thead>
              <tbody>
                {% for i in list %}
                <tr>
                  <td>{{ i.kepanitiaan }}</td>
                  <td>{{ i.organisasi }}</td>
                  <td>{{ i.email }}</td>
                  <td>{{ i.alamat_website }}</td>
                  <td>{{ i.tingkatan }}</td>
                  <td>{{ i.kategori }}</td>
                  <td>{{ i.logo }}</td>
                  <td>{{ i.deskripsi }}</td>
                  <td>{{ i.contact_person }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        {% endif %}
{% endblock %}

simuiWeb/templates/ListOrganisasi.html
{% extends 'layout/base.html' %}
{% load static %}

{% block extension %}SIMUI - List Organisasi{% endblock %}

{% block content %}
{% if request.session.role == "humas" or request.session.role == "admin" %}
<div class="screen5 container py-5">
            <h1>Organisasi</h1> <td><a class="btn btn-success my-2 my-sm-0" style="position: relative; left: 80rem; bottom: 3rem" type="submit" role="button" href="{% url 'core:create_organisasi' %}" >Tambah Organisasi</a>
        
            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Nama Organisasi</th>
                  <th scope="col">Email</th>
                  <th scope="col">Website</th>
                  <th scope="col">Tingkatan</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Logo</th>
                  <th scope="col">Deskripsi</th>
                  <th scope="col">Contact Person</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for i in list %}
                <tr>
                  <td>{{ i.nama }}</td>
                  <td>{{ i.email }}</td>
                  <td>{{ i.alamat_website }}</td>
                  <td>{{ i.tingkatan }}</td>
                  <td>{{ i.kategori }}</td>
                  <td>{{ i.logo }}</td>
                  <td>{{ i.deskripsi }}</td>
                  <td>{{ i.contact_person }}</td>
                  <td><a class="btn btn-primary my-2 my-sm-0" type="submit" role="button" href="{% url 'core:update_organisasi' id=i.id %}">Update</a><a href="{% url 'core:delete_organisasi' i.id %}" id="delete" class="btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
{% else %}
<div class="screen5 container py-5">
            <h1>Organisasi</h1>
        
            <table class="table table-bordered bg-light">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Nama Organisasi</th>
                  <th scope="col">Email</th>
                  <th scope="col">Website</th>
                  <th scope="col">Tingkatan</th>
                  <th scope="col">Kategori</th>
                  <th scope="col">Logo</th>
                  <th scope="col">Deskripsi</th>
                  <th scope="col">Contact Person</th>
                </tr>
              </thead>
              <tbody>
               {% for i in list %}
                <tr>
                  <td>{{ i.nama }}</td>
                  <td>{{ i.email }}</td>
                  <td>{{ i.alamat_website }}</td>
                  <td>{{ i.tingkatan }}</td>
                  <td>{{ i.kategori }}</td>
                  <td>{{ i.logo }}</td>
                  <td>{{ i.deskripsi }}</td>
                  <td>{{ i.contact_person }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endif %}        
        <!-- Scripts -->
        
        <!-- End of Scripts -->
    
{% endblock %}